apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl: 
    manifests:
      - infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: shehriyar027/auth
      context: auth            
      docker:
        dockerfile: dockerfile
      sync:
        manual:
          - 


# Context: Folder that contains the image
# artifacts: what to do inside the build